### ISSUE TITLE
Python 3.8.3 and MacOSx are not supported

### ISSUE THREAD

**Issue by sjunges** [marcoeilers/nagini#143]
Hi,

For future reference; I know that neither Mac nor Python 3.8 are officially supported.
I tried installing this with python 3.8.3 under MacOSx, and failed with the following error message.

> Running setup.py install for typed-ast ... error
>     ERROR: Command errored out with exit status 1:
>      command: /Users/sjunges/.pyenv/versions/3.8.2/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7v/9j_1rhzs1ts4cky4d4tm1vtr0000gn/T/pip-install-loy8g1zk/typed-ast/setup.py'"'"'; __file__='"'"'/private/var/folders/7v/9j_1rhzs1ts4cky4d4tm1vtr0000gn/T/pip-install-loy8g1zk/typed-ast/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7v/9j_1rhzs1ts4cky4d4tm1vtr0000gn/T/pip-record-6dnlcvvd/install-record.txt --single-version-externally-managed --compile
>          cwd: /private/var/folders/7v/9j_1rhzs1ts4cky4d4tm1vtr0000gn/T/pip-install-loy8g1zk/typed-ast/
>     Complete output (23 lines):
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.macosx-10.14-x86_64-3.8
>     creating build/lib.macosx-10.14-x86_64-3.8/typed_ast
>     copying typed_ast/ast35.py -> build/lib.macosx-10.14-x86_64-3.8/typed_ast
>     copying typed_ast/conversions.py -> build/lib.macosx-10.14-x86_64-3.8/typed_ast
>     copying typed_ast/__init__.py -> build/lib.macosx-10.14-x86_64-3.8/typed_ast
>     copying typed_ast/ast27.py -> build/lib.macosx-10.14-x86_64-3.8/typed_ast
>     running build_ext
>     building '_ast27' extension
>     creating build/temp.macosx-10.14-x86_64-3.8
>     creating build/temp.macosx-10.14-x86_64-3.8/ast27
>     creating build/temp.macosx-10.14-x86_64-3.8/ast27/Parser
>     creating build/temp.macosx-10.14-x86_64-3.8/ast27/Python
>     creating build/temp.macosx-10.14-x86_64-3.8/ast27/Custom
>     clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -Iast27/Include -I/Users/sjunges/.pyenv/versions/3.8.2/include/python3.8 -c ast27/Parser/acceler.c -o build/temp.macosx-10.14-x86_64-3.8/ast27/Parser/acceler.o
>     ast27/Parser/acceler.c:13:10: fatal error: 'pgenheaders.h' file not found
>     #include "pgenheaders.h"
>              ^~~~~~~~~~~~~~~
>     1 error generated.
>     error: command 'clang' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /Users/sjunges/.pyenv/versions/3.8.2/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7v/9j_1rhzs1ts4cky4d4tm1vtr0000gn/T/pip-install-loy8g1zk/typed-ast/setup.py'"'"'; __file__='"'"'/private/var/folders/7v/9j_1rhzs1ts4cky4d4tm1vtr0000gn/T/pip-install-loy8g1zk/typed-ast/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7v/9j_1rhzs1ts4cky4d4tm1vtr0000gn/T/pip-record-6dnlcvvd/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
> 

If this is a general problem with python 3.8, a warning might be great.

It works with python 3.7.6! 👍 

Best,
Sebastian

**Comment by marcoeilers** [comment]
Yes, Nagini currently doesn't work with Python 3.8 in general because of a dependency to an old version of typed-ast. I'll check if we can easily switch to a newer version, if not, I'll add an explicit warning in the README.

**Comment by marcoeilers** [comment]
I updated the problematic dependencies and released a new version on Pypi. Nagini should now work with Python 3.7 and 3.8 (3.6 is no longer supported), and we finally use an up-to-date version of mypy.
